# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/120w5-_XgdfR1QR2DF0SuI8Z3mtgSsqNH
"""

import math

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import binom
from scipy.stats import uniform

testcases = int(1e7)
num = 0
denom = 0

X = binom.rvs(n=5, p = 0.5, size = testcases)
Y = uniform.rvs(0,1,size = testcases)

Z = X + Y

for i in Z:
    if i <= 2:
      num = num + 1
    if i >= 5:
      denom = denom + 1

probability = num/denom
print(probability)

#Plotting the figure(graph)

cases = ['']

prob_theo = 6
prob_sim = probability

#plt.figure(figsize=(24,16))
#plt.subplots_adjust(left = None, bottom = 0, right = None, top = 1, wspace = None, hspace = None )
x = np.arange(len(cases))
plt.bar(x + 0.00, prob_theo, color = 'b', width = 0.2, label = 'Theoretical')
plt.bar(x + 0.2, prob_sim, color = 'g', width = 0.2, label = 'Simulated')
plt.xlabel('Theoretical v/s Simulated')
plt.ylabel('Probability')
plt.xticks(x  + 0.2/2,[''])


a = np.arange(0,6.5,0.1)
plt.yticks(a)
plt.ylim([5.5,6.5])
#plt.margins(0.01)
plt.grid(b = True, color ='black', linestyle ='-.', linewidth = 0.5, alpha = 0.2)

plt.legend()
plt.show()